// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrquestadorApi.Data;

#nullable disable

namespace OrquestadorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008232112_AddProjectContexts")]
    partial class AddProjectContexts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrquestadorApi.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.HasKey("ProjectId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("OrquestadorApi.Models.ProjectContext", b =>
                {
                    b.Property<int>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("context_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContextId"));

                    b.Property<string>("InitialPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_prompt");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("ContextId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("contexts");
                });

            modelBuilder.Entity("OrquestadorApi.Models.ProjectContext", b =>
                {
                    b.HasOne("OrquestadorApi.Models.Project", "Project")
                        .WithOne("Context")
                        .HasForeignKey("OrquestadorApi.Models.ProjectContext", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OrquestadorApi.Models.Project", b =>
                {
                    b.Navigation("Context");
                });
#pragma warning restore 612, 618
        }
    }
}
